### ISSUE TITLE
Associação

### ISSUE THREAD

**Issue by leofrederiche** [lleonardoll/ToDoList#1]
Olá pessoal, eu estava fazendo o to do list que vocês me ensinaram na Designa, achei que estava tudo certo, mais estou com algum problema para associar os Items á Lista. Já procurei mais não achei nada que fosse estranho pra mim... alguma ideia?

**Comment by jmscarpa** [comment]
Esta tendo alguma mensagem de erro? O que esta acontecendo?

Em 17 de maio de 2015 20:51, Leonardo Camp Frederiche <
notifications@github.com> escreveu:

**Comment by leofrederiche** [comment]
Nem uma mensagem de erro, sempre que adicionava um item na lista ele salva mais não exibia, mais já encontrei o problema... Eu não estava salvando o id da lista no item. Vlw João
